[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "robot_description"
version = "0.1.0"
description = "Robot description files for g1 and go2 robot model"
readme = "README.md"
requires-python = ">=3.8"